### ISSUE TITLE
[setting] 프로젝트 세팅

### ISSUE THREAD

**Issue by hyeonjeongs** [team-yello/YELLO-Server#1]

**Comment by devkwonsehoon** [comment]
@all-contributors please add @devkwonsehoon for infrastructure, tests and code.

**Comment by devkwonsehoon** [comment]
@all-contributors 
please add @devkwonsehoon for infrastructure, code.
please add @hyeonjeongs  for code.
please add @euije  for code.

**Comment by devkwonsehoon** [comment]
@all-contributors
please add @devkwonsehoon for infrastructure, code.
please add @hyeonjeongs for code.
please add @euije for code.

**Comment by devkwonsehoon** [comment]
@all-contributors
please add @hyeonjeongs for code.
please add @euije for code.

**Comment by devkwonsehoon** [comment]
https://github.com/all-contributors
please add @devkwonsehoon for infrastructure, code.
please add @hyeonjeongs for code.
please add @euije for code.

**Comment by devkwonsehoon** [comment]
@all-contributors
please add @devkwonsehoon for infrastructure, code.
please add @hyeonjeongs for code.
please add @euije for code.

**Comment by devkwonsehoon** [comment]
@all-contributors please add @euije for code.
